version: '3.7'

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  market-manager:
    image: market-manager
    build:
      context: ./MarketManager
    ports:
      - 8555:8555

  education-manager:
    image: education-manager
    build:
      context: ./EducationManager
    ports:
      - 8556:8556

  membership-manager:
    image: membership-manager
    build:
      context: ./MembershipManager
    ports:
    - 8557:8557

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181