version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - toto
    ports:
      - 2181:2181
    container_name: zookeeper

  market-manager:
    image: market-manager
    networks:
      - toto
    build:
      context: ./MarketManager
    ports:
      - 8555:8555
    environment:
      CONSUMER_URL: localhost:9093
      PRODUCER_URL: localhost:9092

  education-manager:
    image: education-manager
    networks:
      - toto
    build:
      context: ./EducationManager
    ports:
      - 8556:8556
    environment:
      CONSUMER_URL: localhost:9093
      PRODUCER_URL: localhost:9092

  membership-manager:
    image: membership-manager
    networks:
      - toto
    build:
      context: ./MembershipManager
    ports:
      - 8557:8557
    environment:
      CONSUMER_URL: localhost:9093
      PRODUCER_URL: localhost:9092

  kafka:
    image: wurstmeister/kafka
    networks:
      - toto
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPIC: "TestMessage:1:3"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8050:8050"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

networks:
  toto: